pub const IRQLs = enum(u32) {
    IRQL_LOW,
    IRQL_USER_DISPATCH,
    IRQL_KERNEL_DISPATCH,
    IRQL_INTERACTIVE,
    IRQL_DISK,
    IRQL_DEVICE,
    IRQL_PREMPTION_CLOCK,
    IRQL_IPI,
    IRQL_HIGH,
};
