#!/usr/bin/env python3
import sys

def extern_symbol(sym):
    print(f'.extern {sym}')
    print(f'.type {sym}, @function')

def entry_symbol(sym):
    print(f'  .quad {sym}')
    print(f'  .asciz "{sym}"')

ignore = ["Owl_SymbolTable_Start","Owl_SymbolTable_End"]

lines = sys.stdin.readlines()
print("/* Autogenerated by generate_symbols.py script for The Owl Kernel */\n")
for i in lines:
    if i.strip().split(" ")[1].upper() != "T":
        continue
    name = i.strip().split(" ")[2]
    if name in ignore:
        continue
    extern_symbol(name)
print("\n.section .rodata")
print(".global Owl_SymbolTable_Start")
print("Owl_SymbolTable_Start:")
for i in lines:
    if i.strip().split(" ")[1].upper() != "T":
        continue
    name = i.strip().split(" ")[2]
    if name in ignore:
        continue
    entry_symbol(name)
print(".global Owl_SymbolTable_End")
print("Owl_SymbolTable_End:")